// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCfZLGmM3AMcdNk4R9dt2eFdhAeUzlVeU',
    appId: '1:1029745407412:web:6b7c89a502b095ac8eaee1',
    messagingSenderId: '1029745407412',
    projectId: 'academix-flutter',
    authDomain: 'academix-flutter.firebaseapp.com',
    storageBucket: 'academix-flutter.appspot.com',
    measurementId: 'G-B312XQVVDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7W5ykcfHR5Ux7An0ZgZzS8U-ZQNT2IAo',
    appId: '1:1029745407412:android:b7a4d01cffc5eabf8eaee1',
    messagingSenderId: '1029745407412',
    projectId: 'academix-flutter',
    storageBucket: 'academix-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIpOk2sOOq2cjiTFtOgcdH91QzijvNkk',
    appId: '1:1029745407412:ios:543bea5650eb85df8eaee1',
    messagingSenderId: '1029745407412',
    projectId: 'academix-flutter',
    storageBucket: 'academix-flutter.appspot.com',
    iosClientId: '1029745407412-9k7s8sve9ophq6l43mv5qsnf9f5arf6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.academixFlutter',
  );
}
